//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Cost_Estimation
    {
        public int R_ID { get; set; }
        [DataType(DataType.Currency)]
        public string R_name { get; set; }
        public Nullable<decimal> R_cost { get; set; }
        public Nullable<decimal> Total_Cost { get; set; }
        [ForeignKey("P_ID")]
        public Nullable<int> P_ID { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
