//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Project_Team
    {
        public int T_ID { get; set; }
        public string T_Email { get; set; }
        public string T_Role { get; set; }
        public string T_Responsebility { get; set; }
        [ForeignKey("P_ID")]
        public Nullable<int> P_ID { get; set; }
    
        public virtual Project Project { get; set; }
        [NotMapped]
        public List<Account> Acccc { get; set; }
    }
}
