//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Management_System.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Project_Management_SystemEntitiesDB : DbContext
    {
        public Project_Management_SystemEntitiesDB()
            : base("name=Project_Management_SystemEntitiesDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Cost_Estimation> Cost_Estimation { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Project_Details> Project_Details { get; set; }
        public virtual DbSet<Project_Stakeholder> Project_Stakeholder { get; set; }
        public virtual DbSet<Project_Team> Project_Team { get; set; }
    }
}
