//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Project_Details
    {
        public int P_Detail_ID { get; set; }
        [StringLength(255,MinimumLength =5)]
        public string P_Scope { get; set; }
        [StringLength(255, MinimumLength = 5)]
        public string P_Description { get; set; }
        [StringLength(200, MinimumLength = 5)]
        public string P_Objective { get; set; }
        [StringLength(200, MinimumLength = 5)]
        public string P_Goals { get; set; }
        [StringLength(200, MinimumLength = 5)]
        public string P_Oppotunities { get; set; }
        
        public Nullable<System.DateTime> P_StartDate { get; set; }
        public Nullable<System.DateTime> P_EndDate { get; set; }
        public Nullable<int> P_Duration { get; set; }
        [ForeignKey("P_ID")]
        public Nullable<int> P_ID { get; set; }
    
        public virtual Project Project { get; set; }
        public List<Project> Project_list { get; set; }
    }
}
